language: java

jdk:
  - openjdk15

install:
  - git checkout master
  - chmod +x ./autobuild/push-app.sh
after_success:
  - ./autobuild/push-app.sh

script: ./mvnw package -DskipTests

notifications:
  email:
    on_success: change
    on_failure: always