version: "2"

services:
  exchange-service:
    build: .
    ports:
    - "5000:8080"
    environment:
      - GIPHY_APP_ID
      - OPEN_EXCH_RATES_APP_ID
    volumes:
      - ./logs_volume:/usr/exchange-service-app/logs